### ISSUE TITLE
what's a different of correctiq and IQ correct in grc 3.9

### ISSUE THREAD

**Issue by boviz23** [ghostop14/gr-correctiq#16]
Hi guys, i am a beginner of ubuntu and grc but i have something to do with gnuradio and ettus e320. then, I try to remove a DC spike at center frequency and i found gr-correctiq but i tried to install with grc 3.9 but i cannot used this module. grc was showed "ModuleNotFoundError: No module named 'correctiq" same the previous issue. however, I found IQ correct module that preinstall with grc 3.9 already. then, I'd like to know their are same or different function.

if their are a different function, please help me to solve and use it.

**Comment by ghostop14** [comment]
Hi boviz23, in GR 3.9 gr-correctiq was upstreamed into GR.  So you should just use the native ones in GR 3.9.  gr-correctiq is maintained for 3.9 but mainly for backward compatibility for folks that have flowgraphs with it in them already.
