### ISSUE TITLE
Windows GNURadio

### ISSUE THREAD

**Issue by bluegizmo83** [ghostop14/gr-correctiq#7]
How can i install this is the Windows version of GNURadio?

**Comment by ghostop14** [comment]
Hi bluegizmo83, I've actually never been able to get a Windows environment set up to build OOT GNURadio modules but I do believe it's possible.  I think if you follow the instructions to setting up a Windows build environment so you can build any OOT module (try something with some instructions on the Internet already first maybe as an easy test case), then try building it, it may work.  It always seemed like more trouble than just running it in a linux distro though were it's much easier to get the environment set up.

**Comment by olie304** [comment]
Please add a Windows build! A real pain to download 190MB of libraries to build this.

**Comment by ghostop14** [comment]
Good news.  I've been working with the GNURadio folks this year upstreaming a number of modules, and all of the correctiq modules are now in GNU Radio Master slated to be GR 3.9.  So they'll be available natively on Windows when it's released.
