### ISSUE TITLE
Does not build for gnuradio 3.8

### ISSUE THREAD

**Issue by sceneryexplosion** [ghostop14/gr-correctiq#9]

**Comment by ghostop14** [comment]
morning sceneryexplosion..... no it doesn't.  Just last week I set up a dev environment to start migrating modules to 3.8 and I do expect a few challenges along the way.  Keep an eye out going into the beginning of October for 3.8-compatible versions.

**Comment by sceneryexplosion** [comment]
Love to hear that. One of my absolute favorite OOT:s. Keep up the great work!

**Comment by ghostop14** [comment]
Thanks!  As soon as I get back from GRCon conversion is my next project :)

**Comment by ghostop14** [comment]
sceneryexplosion: I spent some time yesterday and I was able to get it converted over to 3.8.  I just submitted a pybombs pull, so the recipe changes are not in there yet.  But if you clone master now, it's the 3.8 branch.  The 3.7 branch is now tagged as the maint-3.7 branch.  Tested all blocks and seems good.

**Comment by sceneryexplosion** [comment]
Wow, that's some fast support ;) great work and thank you for a great job! got i building from source, no problems at all
